chore(client): Added a first prototype of check version
Codename-Recon/Gridlock pull request #119
Opened 2024-06-14 16:03 UTC by Dracks

2024-06-15 09:17 UTC, HunterNN commented
I recommend utilizing the global scene `logic/globals/messages.tscn` for incorporating such dialogues, either by using an existing accept dialog or creating another one based on a `Window`. I also suggest reviewing the script attached to that scene.

To replace the button for new version updates: When the game checks for a new update, it should display this dialogue. The check is performed at the start of the game or when the player clicks on the version label. If the user clicks on the version label and the current version matches, the game can also provide a message stating that the latest version is up to date. Should the detected version not be in "v..." format, it should indicate that this isn't a release version hence cannot identify new updates. The dialogue could include an option for accessing the release page in that situation.

Regarding translation keys appearing: Will they be resolved when this PR gets merged?
![image](https://github.com/Codename-Recon/Codename-Recon/assets/1898454/9f8625a7-8ab2-4c9a-a05d-515e8c8d2d35)

2024-06-15 09:27 UTC, HunterNN commented
Also this plugin could be interesting: https://github.com/daenvil/MarkdownLabel

2024-07-12 15:11 UTC, HunterNN requested changes

2024-07-12 15:11 UTC, HunterNN commented on client/logic/ui/new_version_checker.gd
> +	func _init(data: String)->void:
File needs also to be formatted by the formatter. (Missing spaces before and after `->`)

2024-07-13 07:01 UTC, Dracks commented on client/logic/ui/components/button_to_uri.gd
> +class_name ButtonToUri
I usually use this order, the samples from godot (If I remember correctly) were in this order. I can change it.

2024-07-13 07:03 UTC, Dracks commented on client/logic/ui/new_version_checker.gd
> +var messages: GlobalMessages = $"/root/Messages"
I didn't knew this way to reference an autoload. Thanks!

2024-07-15 18:58 UTC, Dracks commented on client/logic/globals/messages.tscn
> +* I don't know
if we don't get the version from the repo, this message should not be shown ever.

2024-07-28 12:03 UTC, HunterNN commented on client/logic/globals/messages.tscn
> +* I don't know
Still, it feels a bit unprofessional to use those placeholders. I'd suggest using generic text about the text not loading correctly, like you did with the credits.

2024-07-29 05:52 UTC, Dracks commented on client/logic/globals/messages.tscn
> +* I don't know
I will change it, but part of this placeholder was to validate the texts is shown correctly

2024-07-30 08:49 UTC, HunterNN approved these changes

2024-07-30 08:54 UTC, merged